Create Game Class and Author Class
Fene-87/catalog_of_things pull request #41
Opened 2023-04-26 14:46 UTC by Fene-87

### In this project milestone, I have accomplished the following:
- Create a Game class in a separate .rb file.
- Define all Game class properties visible in the diagram and set them up in the constructor method.
- Implement "can_be_archived?" method in the Game class.
- Create an Author class with an association to the Item class in a separate .rb file.
- Define all Author class properties visible in the diagram and set them up in the constructor method.

2023-04-26 16:35 UTC, shasherazi commented on classes/game.rb
> +    super && last_played_at > 2
the variable `last_played_at` is in date format. To check whether it is older than 2 years or not you will have to subtract the `publish_date` from `Date.now` and check if the gap is greater than two years. You can see it how I did it in the `Movie` class.

2023-04-26 16:36 UTC, shasherazi requested changes
Great effort, however, there is still room for improvement. See comments.

2023-04-26 21:41 UTC, Fene-87 commented on classes/game.rb
> +    super && last_played_at > 2
It is not present in your movie class.

2023-04-27 05:12 UTC, shasherazi commented on classes/game.rb
> +    super && last_played_at > 2
Oh I am really sorry @Fene-87 . I meant to say `Item` class. See the lines I am quoting. 3652 is the number of days in 10 years. You can do the same to calculate 2 years.
https://github.com/Fene-87/catalog_of_things/blob/dev/classes/item.rb#L34-L36

2023-04-27 05:14 UTC, shasherazi approved these changes
Great work; everything looks good to me. Time to merge.

2023-04-27 06:58 UTC, merged